const Corinthians = [
  //Normais
  {
    name: "Angel Romero",
    Defesa: 30,
    Control: 75,
    Ataque: 80,
    Over: 193,
    front: "Corinthians/AngelRomero.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Memphis Depay",
    Defesa: 30,
    Control: 85,
    Ataque: 91,
    Over: 192,
    front: "Corinthians/MemphisDepay.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Matias Rojas",
    Defesa: 32,
    Control: 75,
    Ataque: 70,
    Over: 203,
    front: "Corinthians/MatiasRojas.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Matheus Bidu",
    Defesa: 70,
    Control: 68,
    Ataque: 60,
    Over: 183,
    front: "Corinthians/Matheus Bidu.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Raniele",
    Defesa: 75,
    Control: 70,
    Ataque: 42,
    Over: 180,
    front: "Corinthians/Ranielecard.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Garro",
    Defesa: 50,
    Control: 85,
    Ataque: 78,
    Over: 191,
    front: "Corinthians/Garro10.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Fágner",
    Defesa: 85,
    Control: 75,
    Ataque: 55,
    Over: 190,
    front: "Corinthians/Fagner.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Pedro Raul",
    Defesa: 20,
    Control: 62,
    Ataque: 70,
    Over: 187,
    front: "Corinthians/PedroRaulcard.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Talles Magno",
    Defesa: 30,
    Control: 70,
    Ataque: 72,
    Over: 190,
    front: "Corinthians/TallesMagno.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Yuri Alberto",
    Defesa: 41,
    Control: 76,
    Ataque: 82,
    Over: 193,
    front: "Corinthians/YuriAlbertocard.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Cássio",
    Defesa: 85,
    Control: 60,
    Ataque: 42,
    Over: 168,
    front: "Corinthians/Cassio.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  //Idolos
  {
    name: "Paulinho",
    Defesa: 70,
    Control: 85,
    Ataque: 82,
    Over: 220,
    front: "Corinthians/Paulinho.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Renato Augusto",
    Defesa: 60,
    Control: 85,
    Ataque: 89,
    Over: 233,
    front: "Corinthians/RenatoAugustoCard.png",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Rivellino",
    Defesa: 40,
    Control: 92,
    Ataque: 95,
    Over: 217,
    front: "Corinthians/Rivelinno.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  {
    name: "Ronaldo",
    Defesa: 40,
    Control: 92,
    Ataque: 99,
    Over: 222,
    front: "Corinthians/RonaldoCard.jpg",
    back: "Corinthians/FundoCarta.png",
  },
  // Adicione mais cartas conforme necessário
];

const CorinthiansINFO = [
  // Clube
  (Tier = 2),
  // Estádio
  (estádio = "NEO Quimica Arena"),
  (capacidade = 48905),
  (valor_ingresso = 50),
];
